spring:
  cloud:
    config:
      server:
        native:
          searchLocations: file:///C:/develop/repository/git/example/spring-config-server/repository-native/config/{label}/{application}
          addLabelLocations: true
